# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: istheweb.shop::lang.category.label

# Model Form Field configuration
form: $/istheweb/shop/models/category/fields.yaml

# Model Class name
modelClass: Istheweb\Shop\Models\Category

# Default redirect location
defaultRedirect: istheweb/shop/categories

# Create page
create:
    title: istheweb.shop::lang.category.create_title
    redirect: istheweb/shop/categories/update/:id
    redirectClose: istheweb/shop/categories

# Update page
update:
    title: istheweb.shop::lang.category.create_title
    redirect: istheweb/shop/categories
    redirectClose: istheweb/shop/categories

# Preview page
preview:
    title: istheweb.shop::lang.category.preview_title